Initial implementation
SparkPost/sendgrid-sparkpost-templates pull request #1
Opened 2017-04-19 15:57 UTC by rajumsys

Initial implementation of SendGrid to SparkPost template migration

- Read the readme.md for setup instruction

**ToDos**

- [ ] A few regex might be incomplete
- [x] Cleanup and remove mandrill specific info
- [x] Make repo public 
- [x] Unit tests

**After merge ToDos**
- [ ] Update Heroku deploy button to use master branch

Temporary Demo: https://sendgrid-sparkpost.herokuapp.com/

2017-04-21 12:05 UTC, ewandennis commented
Fast work! Coupla general comments:
 - lets split the transactional and marketing translation flows to show we know the difference
 - ask for just 1 transactional substitution delimiter unless you have evidence to the contrary
 
I haven't looked at tests yet. Will put some templates and campaigns through it today and review the actual translation logic.

2017-04-21 12:06 UTC, ewandennis requested changes
Fast work! Coupla general comments:
 - lets split the transactional and marketing translation flows to show we know the difference
 - ask for just 1 transactional substitution delimiter unless you have evidence to the contrary
 
I haven't looked at tests yet. Will put some templates and campaigns through it today and review the actual translation logic.

2017-04-21 12:06 UTC, ewandennis commented on README.md
> +git clone --recursive https://github.com/SparkPost/sendgrid-sparkpost-templates.git
Do we need `--recursive`?

2017-04-21 12:06 UTC, ewandennis commented on README.md
> +- Sender Info
What is `Sender Info`?

2017-04-21 12:06 UTC, ewandennis commented on README.md
> +## Supported Features
Should we explain that these are chunks of syntax we support and separate them into "transactional" and "marketing" template types?

2017-04-21 12:06 UTC, ewandennis commented on README.md
> +You need provide the names of the custom delimited variables during translation. Only one type of delimiter is supported.
"You need to provide" or "You must nominate"

I thought we were asking for delimiters rather than variable names? If so, how about

"You must nominate your chosen substitution variable delimiter since SendGrid has no standardised substitution syntax."

2017-04-21 12:06 UTC, ewandennis commented on README.md
> +You can deploy it directly to Heroku: [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/SparkPost/sendgrid-sparkpost-templates/tree/develo
Note to remember this will need changed prior to release: it points to the develop branch.

2017-04-21 12:06 UTC, ewandennis commented on README.md
> +  "beginDelimiter": "string",
Unless you have examples which use different start and end delimiters, let's keep it simple and ask for just one.

2017-04-21 12:06 UTC, ewandennis commented on README.md
> +  "sengridIsCampaign": "boolean"
Maybe "templateType" with values "transactional" or "marketing" ?

2017-04-21 12:06 UTC, ewandennis commented on README.md
> +{
We'll need a transactional substitution delimiter field here too.

2017-04-21 12:06 UTC, ewandennis commented on bower.json
> +    "Mohammad Hossain <mohammad.hossain@sparkpost.com>"
Hey! What about me? :)

2017-04-21 12:06 UTC, ewandennis commented on lib/sparkpost.js
> +      console.log('here');
Did I leave these behind? Would you mind tidying up after my messiness?

2017-04-21 12:06 UTC, ewandennis commented on lib/sparkpost.js
> +      console.log('here 2');
Same here :)

2017-04-21 12:06 UTC, ewandennis commented on lib/translate.js
> +var translationRules = [
Can/should we separate out transactional and marketing campaign translation rules?

2017-04-21 12:06 UTC, ewandennis commented on lib/translate.js
> +    delimiterRegex = new RegExp(`(\\${opts.beginDelimiter}{1}(\\w+)\\${opts.endingDelimiter}{1})`, 'gi');
Deliberately case-insensitive?

2017-04-21 12:06 UTC, ewandennis commented on static/index.html
> +            <h4>Supported Features</h4>
The supported and unsupported lists are looking rough. Can we grow the panels they live in to accommodate the text and/or make it clear that we mean "supported template syntax" specifically?

2017-04-21 12:06 UTC, ewandennis commented on static/index.html
> +                <li><strong>Needs extra info (Links after translation is done)</strong><br>
What does "needs extra info" mean?

2017-04-21 12:06 UTC, ewandennis commented on static/index.html
> +                <li><strong>User delimited variables</strong><br> You need to specify the custom delimiters that you've used in your template.
Lets include the word "substitution" since it's what SendGrid uses.

2017-04-21 12:06 UTC, ewandennis commented on static/migrate.html
> +                  <th class="pull-right">SendGrid Template/Marketing Campaign ID</th>
This is long and tricky to read. Let's say something "Template ID" on the left and just "Transactional template or campaign ID" on the right.

2017-04-21 12:06 UTC, ewandennis commented on static/migrate.html
> +                <div class="checkbox">
Maybe a dropdown or 2-state button?

2017-04-21 12:06 UTC, ewandennis commented on static/translate.html
> +          <label>Custom delimiter<br/>
What can we do to clean up the delimiter field? Some ideas:

 - ask for just 1 delimiter
 - prefill with common delimiters from the docs (e.g. `-`, `%`)
 - separate out transactional and marketing campaign translation flows

2017-04-21 14:16 UTC, rajumsys commented on README.md
> +You can deploy it directly to Heroku: [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/SparkPost/sendgrid-sparkpost-templates/tree/develo
Yeah, it's in ToDo list in the PR description

2017-04-21 14:17 UTC, rajumsys commented on README.md
> +git clone --recursive https://github.com/SparkPost/sendgrid-sparkpost-templates.git
i don't think we need it. came from previous repo

2017-04-21 14:26 UTC, rajumsys commented on README.md
> +  "beginDelimiter": "string",
In their [documentation](https://sendgrid.com/docs/API_Reference/SMTP_API/section_tags.html) they say

> In some cases -subVal- may be the best choice while in other cases, %subVal%, #subVal#, or :subVal may make more sense. The flag doesn’t matter, as long as it’s a unique string.

So, how we'll distinguish, whether it's `:name:` or `:name` if we ask for one delimiter?  I've an alternative in mind but that _may end up being_ complex.

2017-04-21 14:28 UTC, rajumsys commented on lib/sparkpost.js
> +      console.log('here');
nah, i might have add me. `here` is my thing :P.

2017-04-21 14:30 UTC, rajumsys commented on lib/translate.js
> +    delimiterRegex = new RegExp(`(\\${opts.beginDelimiter}{1}(\\w+)\\${opts.endingDelimiter}{1})`, 'gi');
should they be sensitive? but it should not probably have any affect here due to `w+`.

2017-04-21 14:30 UTC, rajumsys commented on static/index.html
> +                <li><strong>Needs extra info (Links after translation is done)</strong><br>
That's in brace. 
> Links after translation is done

2017-04-21 14:32 UTC, rajumsys commented on README.md
> +## Supported Features
sounds good

2017-04-21 14:34 UTC, rajumsys commented on README.md
> +- Sender Info
`Sender_Name, Sender_Address, Sender_City, Sender_State, Sender_Zip` not clear enough? I had put them all initially but then thought too verbose.

2017-04-21 14:35 UTC, rajumsys commented on README.md
> +You need provide the names of the custom delimited variables during translation. Only one type of delimiter is supported.
This is old text (before our review, i'll fix it to add delimiter, not variable). And will add that `to`.

2017-04-21 14:43 UTC, rajumsys commented on lib/translate.js
> +var translationRules = [
i guess a comment separating these two should be fine?

2017-04-21 16:21 UTC, rajumsys commented on bower.json
> +    "Mohammad Hossain <mohammad.hossain@sparkpost.com>"
npm didn't support multiple author(s), so overlooked it's an array. i'll add in both places :).

2017-04-24 15:02 UTC, ewandennis commented on README.md
> +- Sender Info
Let's be explicit.

2017-04-24 15:02 UTC, ewandennis commented on README.md
> +  "beginDelimiter": "string",
Let's ask for 1 delimiter and let people choose between single- or double-delimited variables.

2017-04-24 15:03 UTC, ewandennis commented on lib/translate.js
> +var translationRules = [
I'd rather we applied each rule set completely independently of the other to avoid any unexpected results.

2017-04-24 15:04 UTC, ewandennis commented on static/index.html
> +                <li><strong>Needs extra info (Links after translation is done)</strong><br>
I didn't understand that either :)

2017-04-24 15:04 UTC, ewandennis commented
Getting there - maybe a quick chat this week to get it finished up?

2017-04-27 16:34 UTC, rajumsys commented on static/migrate.html
> +                <div class="checkbox">
I didn't do it. Let me know if you still think this way after this revision. I can modify it.

2017-04-27 20:08 UTC, rajumsys commented
@ewandennis Addressed review feedbacks and updated tests accordingly. Let me know if you've further feedbacks.

2017-05-03 23:19 UTC, merged